name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup
        run: npm ci

      # - name: Install Gulp
      #   run: npm install gulp-cli -g

      - name: Build project
        run: npx gulp
